### ISSUE TITLE
App always freezing When i modify function  arguments

### ISSUE THREAD

**Issue by chile-zhong** [iGio90/Dwarf#2]
App always freezing When i modify function  arguments

**Comment by iGio90** [comment]
Native hook? 
Latest commit? (Update dwarf as I did many fixes those days)

**Comment by chile-zhong** [comment]
> Native hook?
> Latest commit? (Update dwarf as I did many fixes those days)

In java hook.
By the way, after update dward, no matter windows or linux , both show error when install keystone:
scrypt-1.2.1/libcperciva/crypto/crypto_aes.c:6:25: fatal error: openssl/aes.h: No such file or directory

**Comment by iGio90** [comment]
Yeah keystone is a bit tricky to install also on a Mac. Dig the error in Google! About the args.. I think it's fine. I mean. I didn't yet coded the logic for change java hook. Gonna keep this issue open until I implement it. Gonna do it between today and tomorrow :) please hit me up if you find anything else!

**Comment by iGio90** [comment]
Please, refer to this commit -> https://github.com/iGio90/Dwarf/commit/ab24458999e23c76f8c272915b456d6ee1d452da

The ability to change values through ui has been removed. 
On the java side, i've added an additional column to display java argument class.
On both, java and native, the console in dwarf now expose the object ``this.context`` (as frida does), which allows you to play with arguments.

you can type something like ``console.log(JSON.stringify(this.context))`` in the console to find out that there is a "value" variable which you can edit to apply your changes.

-> Hook logic expose this.context as well.

Note, im going to add soon a button to pop a multiline text editor as input for the console. This because when you want to touch java args you will mostly need to something like
```
Java.perform(function ...
var arg = Java.use('java.lang.String');
ecc ecc
```
which is bad to do on a single line input.

If you have further questions, please ask or ping on slack!
